spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb?options=-c%20TimeZone=Asia/Kolkata
    username: riskuser
    password: riskpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"