server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false   # optional but recommended

  flyway:
    enabled: true         # ensure migrations run properly

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: mysupersecretkeymysupersecretkey12345
  expiration: 86400000