spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riskdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: false   # disable for now

management:
  endpoints:
    web:
      exposure:
        include: "*"